export const categories = [
  {
    id: 'fruit',
    title: 'Fruit Green Tea',
    items: [
      { name: 'Butterfly Pea Lemon (16oz)', price: '$5.99', desc: 'Refreshing green tea infused with butterfly pea and lemon', allergies: 'Lemons' },
      { name: 'Honey Lemon Green Tea', price: '$6.35', desc: 'Green tea with a sweet touch of honey and tangy lemon.', allergies: 'Lemon, Honey' },
      { name: 'Lychee Green Tea', price: '$6.35', desc: 'Green tea with the exotic flavor of lychee.', allergies: 'Lychee' },
      { name: 'Mango Green Tea', price: '$6.35', desc: 'Green tea infused with tropical mango flavors.', allergies: 'Mango' },
      { name: 'Passionfruit Green Tea', price: '$6.35', desc: 'Green tea with the zesty essence of passionfruit.', allergies: 'Passionfruit' },
      { name: 'Pineapple Green Tea', price: '$6.35', desc: 'Green tea with a hint of pineapple sweetness.', allergies: 'Pineapple' },
      { name: 'Peach Green Tea', price: '$6.35', desc: 'Green tea with the delicate flavor of peach.', allergies: 'Peach' },
      { name: 'Rose Green Tea', price: '$6.35', desc: 'Green tea infused with floral notes of rose.', allergies: 'Rose' },
      { name: 'Strawberry Green Tea', price: '$6.35', desc: 'Green tea with a fruity strawberry twist.', allergies: 'Strawberry' },
    ],
  },
  {
    id: 'sparkling',
    title: 'Sparkling Fruit Tea',
    items: [
      { name: 'Lychee Sparkling Tea', price: '$6.35', desc: 'Green tea with the exotic flavor of lychee, but sparkling', allergies: 'Lychee' },
      { name: 'Mango Sparkling Tea', price: '$6.35', desc: 'Green tea infused with tropical mango flavors, but sparkling', allergies: 'Mango' },
      { name: 'Passionfruit Sparkling Tea', price: '$6.35', desc: 'Green tea with the zesty essence of passionfruit, but sparkling', allergies: 'Passionfruit' },
      { name: 'Pineapple Sparkling Tea', price: '$6.35', desc: 'Green tea with a hint of pineapple sweetness, but sparkling', allergies: 'Pineapple' },
      { name: 'Peach Sparkling Tea', price: '$6.35', desc: 'Green tea with the delicate flavor of peach, but sparkling', allergies: 'Peach' },
      { name: 'Rose Sparkling Tea', price: '$6.35', desc: 'Green tea infused with floral notes of rose, but sparkling', allergies: 'Rose' },
      { name: 'Strawberry Sparkling Tea', price: '$6.35', desc: 'Green tea with a fruity strawberry twist, but sparkling', allergies: 'Strawberry' },
    ],
  },
  {
    id: 'hot',
    title: 'Hot Drinks (12oz)',
    items: [
      { name: 'Americano', price: '$4.50', desc: 'A classic espresso-based coffee with a robust flavor.', allergies: 'Caffeine' },
      { name: 'Cappuccino', price: '$4.50', desc: 'A classic espresso-based coffee with a robust flavor.', allergies: 'Caffeine' },
      { name: 'Caramel Macchiato', price: '$4.75', desc: 'Espresso with steamed milk and a caramel drizzle.', allergies: 'Caffeine, Milk' },
      { name: 'Hazelnut Macchiato', price: '$4.75', desc: 'Espresso and steamed milk with hazelnut flavor.', allergies: 'Caffeine, Milk' },
      { name: 'Latte', price: '$4.50', desc: 'Espresso blended with steamed milk for a creamy texture.', allergies: 'Caffeine, Milk' },
      { name: 'Vanilla Latte', price: '$4.50', desc: 'Espresso and steamed milk with vanilla flavor.', allergies: 'Caffeine, Milk' },
      { name: 'Caramel Latte', price: '$4.50', desc: 'Espresso and steamed milk with caramel syrup.', allergies: 'Caffeine, Milk' },
      { name: 'Black Sugar Latte', price: '$4.75', desc: 'Espresso and steamed milk with black sugar syrup.', allergies: 'Caffeine, Milk' },
      { name: 'Hot Chocolate', price: '$4.75', desc: 'Rich and creamy chocolate drink served hot.', allergies: 'Chocolate, Milk' },
      { name: 'Mocha Latte', price: '$4.75', desc: 'Espresso and steamed milk with mocha flavor.', allergies: 'Caffeine, Chocolate, Milk' },
      { name: 'Matcha Latte', price: '$4.75', desc: 'Japanese matcha green tea with steamed milk.', allergies: 'Milk' },
      { name: 'Chai Latte', price: '$4.75', desc: 'Black tea with chai spices and steamed milk.', allergies: 'Milk' },
      { name: 'Pistachio Latte', price: '$4.75', desc: 'Espresso and steamed milk with pistachio flavor.', allergies: 'Caffeine, Milk' },
    ],
  },
  {
    id: 'iced',
    title: 'Iced Drinks (16oz)',
    items: [
      { name: 'Iced Americano', price: '$5.00', desc: 'Chilled version of espresso-based Americano.', allergies: 'Caffeine' },
      { name: 'Iced Cappuccino', price: '$5.00', desc: 'Iced version of the classic cappuccino.', allergies: 'Caffeine' },
      { name: 'Iced Caramel Macchiato', price: '$5.50', desc: 'Chilled espresso with caramel and milk.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Hazelnut Macchiato', price: '$5.75', desc: 'Chilled espresso with hazelnut flavor and milk.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Latte', price: '$5.50', desc: 'Classic iced espresso and milk.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Vanilla Latte', price: '$5.50', desc: 'Iced latte with vanilla syrup.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Caramel Latte', price: '$5.50', desc: 'Iced latte with caramel syrup.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Hazelnut Latte', price: '$5.75', desc: 'Iced latte with hazelnut flavor.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Black Sugar Latte', price: '$5.50', desc: 'Iced latte with black sugar syrup.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Mocha Latte', price: '$5.75', desc: 'Iced latte with mocha flavor.', allergies: 'Caffeine, Chocolate, Milk' },
      { name: 'Iced Matcha Latte', price: '$5.75', desc: 'Iced Japanese matcha tea and milk.', allergies: 'Milk' },
      { name: 'Iced Pistachio Latte', price: '$5.75', desc: 'Iced latte with pistachio flavor.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Mousse Latte', price: '$5.75', desc: 'Iced latte topped with mousse foam.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Rose Latte', price: '$5.75', desc: 'Iced latte infused with rose flavor.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Tiramisu Latte', price: '$5.75', desc: 'Iced latte with tiramisu-inspired flavor.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Dalgona Latte', price: '$5.75', desc: 'Iced latte topped with whipped coffee.', allergies: 'Caffeine, Milk' },
      { name: 'Iced Chai Latte', price: '$5.50', desc: 'Iced version of chai latte with milk.', allergies: 'Milk' },
    ],
  },
];
